### ISSUE TITLE
Is there any option to sign-up using invite code?

### ISSUE THREAD

**Issue by tandav** [stypr/clubhouse-py#4]
```
 python3 cli.py
[.] Please enter your phone number. (+818043217654) > +12345678900
[.] Please enter the SMS verification code (1234, 0000, ...) > 0000
[.] Writing configuration file complete.
[!] You're still on the waitlist. Find your friends to get yourself in.
Traceback (most recent call last):
  File "/Users/tandav/Desktop/clubhouse-py/cli.py", line 326, in <module>
    main()
  File "/Users/tandav/Desktop/clubhouse-py/cli.py", line 323, in main
    main()
  File "/Users/tandav/Desktop/clubhouse-py/cli.py", line 319, in main
    chat_main(client)
  File "/Users/tandav/Desktop/clubhouse-py/cli.py", line 150, in chat_main
    print_channel_list(client, max_limit)
  File "/Users/tandav/Desktop/clubhouse-py/cli.py", line 83, in print_channel_list
    channels = client.get_channels()['channels']
KeyError: 'channels'```

**Comment by stypr** [comment]
You need someone to invite you to Clubhouse.
It's not like you can sign up using an invite coupon or acode.
